---
- name: Configure nginx to forward request to Archivax
  hosts: nginx
  become: True
  tasks:
    - name: copy archiva.conf to remote
      copy:
        src: ./archiva.conf
        dest: /etc/nginx/conf.d/archiva.conf
        owner: centos
        group: centos
        mode: u=rw,g=r,o=r
    
    - name: disable nginx default.conf
      shell: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disable

    - name: restart nginx server
      service: name=nginx state=restarted
